#hexmap_builder_tables.py

#See Tables on page 26 of Rulebook
hex_type=["Countryside","Countryside","Forest","Forest","Forest","River","Humantown"]
countryside_landmarks=[
	"Anthill",
	"Beech, lightning split",
	"Bone-white tree",
	"Cow skeleton",
	"Field of flowers",
	"Field of wheat",
	"Hedge row",
	"Hollow tree stump",
	"Huge flat rock",
	"Lily-lined pond",
	"Massive fallen tree",
	"Old craggy oak",
	"Old farmhouse",
	"Quiet dirt road",
	"Rabbit warren",
	"Sparrow nest",
	"Stand of pine trees",
	"Steep hill",
	"Stone wall",
	"Tangle of fig roots"
]
forest_landmarks=[
	"Abandoned shack",
	"Bright clearing",
	"Cascading waterfalls",
	"Cliff face",
	"Cold, fresh spring",
	"Dense underbrush",
	"Face in ancient oak",
	"Fox hole",
	"Grove of ferns",
	"Hollow tree stump",
	"Huge pine tree",
	"Human walking track",
	"Human-made clearing",
	"Meandering brook",
	"Overgrown ruins",
	"Ring of stones",
	"Rocky outcropping",
	"Sunken hollow",
	"Tangle of roots",
	"Termite-riddled tree"
]
river_landmarks=[
	"Canal lock",
	"Converging tributaries",
	"Draping willow",
	"Eroded riverbank",
	"Fallen tree crossing",
	"High waterfall",
	"Huge boulder",
	"Huge concrete dam",
	"Isolated island",
	"Muddy flats",
	"Rocky rapids",
	"Row of dead trees",
	"Silty dam",
	"Stepping-stones",
	"Stone bridge",
	"Stony shallows",
	"Submerged trash",
	"Sunken barge",
	"Twisted roots",
	"Wooden bridge"
]
humantown_landmarks=[
	"Abandoned car",
	"Apartment balcony",
	"Blackberry hedge",
	"Busy road",
	"Drainpipe outlet",
	"Dumped furniture",
	"Greenhouse",
	"Mouse ruins",
	"Newly built house",
	"Overgrown garden bed",
	"Pigeon nest",
	"Pile of trash",
	"Rocky riverbed",
	"Shopping trolley",
	"Stagnant pond",
	"Steel bridge",
	"Trash-filled skip",
	"Tree-lined footpath",
	"Underground car park",
	"Woodshed"
]

#See Table on page 27 of Rulebook (Mouse settlement handled in source code by rolling d6)
landmark_details = [
	"Small mouse farm (What threatens their crops?)",
	"Noblemouse’s castle (What does it defend against?)",
	"Friendly mouse roadhouse (What is in the basement?)",
	"Mouse hunting lodge (What is their quarry?)",
	"Mining outpost (What have they uncovered?)",
	"Mouse hermit’s hut (Why do they shun society?)",
	"Natural caves (What is living here?)",
	"Hedge-knight’s tower (What is their quest?)",
	"Songbird’s nest (What sad tales do they sing of?)",
	"Tribe of huge, peaceful beasts (What do they fear?)",
	"Rat bandit hideout (Who do they prey on?)",
	"Crow coven’s spire (What spells do they caw?)",
	"Hive of insects (What do they hunger for?)",
	"Den of a great predator (What treasure do they guard?)",
	"Frog fortress (What lies hidden in the dungeon?)",
	"Mouse wizard’s tower (What is spell almost finished?)",
	"Dangerous natural feature (How can it be avoided?)",
	"Lonely shrine (Who maintains it? What do they worship?)",
	"Noblemouse’s manor (Why was it abandoned?)",
	"Abandoned settlement (What clues did they leave?)",
	"Ruined watchtower (What did it guard from?)",
	"Natural feature, peaceful and safe (Who gathers here?)",
	"Natural feature, out of place (How did it form?)",
	"Rickety bridge (What does it cross over?)",
	"Ancient bat cult temple (What was summoned?)",
	"Faerie ring (What business do the faeries have here?)",
	"Beetle graveyard (What do the ghosts want?)",
	"Mouse witch’s hut (What does she brew?)",
	"Small, deep pond (What is at the bottom?)",
	"Out-of-season plantlife (Why are they growing here?)",
	"Owl sorcerer’s nest (What are they searching for?)",
	"Strange magical anomaly (Why is it spreading?)",
	"Crashed Lilliputian airship (How can it be repaired?)",
	"Humming stone (What happens when touched?)",
	"Completely lifeless (What disaster has occurred?)",
	"Regularly used by humans (What do they do here?)",
	"Damaged by humans (What have they done?)",
	"Ancient ruins of a past civilisation (Who built this?)",
	"Cat lord’s hunting ground (What trophies remain?)",
	"Repurposed human construction (How is it used?)"
]

#See Table from page 28 of Rulebook
settlement_inhabitants = [
	"Shave elaborate patterns in their fur",
	"Intoxicated by strange plants",
	"Wary of doing business with outsiders",
	"Curious for news from afar",
	"Believe grooming their fur is bad luck",
	"Wear finely embroidered clothes",
	"Brew honey-mead, flavoured with pungent herbs",
	"Cover their faces with long hoods",
	"Impoverished by a cat lord’s tithes",
	"Ceremonially crop their tails",
	"Brave hunters of large beasts",
	"All descended from single matriarch",
	"Bake delicious berry pies",
	"Lab escapees, naive about the world",
	"Spend their days lazing by a stream",
	"Long-standing blood feud with another settlement",
	"Dig grand tunnels, overseen by the guild",
	"Wear large, wide-brimmed hats",
	"Have laws and customs confusing to outsiders",
	"On friendly terms with a predator"
]
settlement_feature = [
	"Maze of defensive, trap-filled tunnels",
	"Exceedingly comfortable, well-appointed inn",
	"Shrine carved of black wood",
	"Meditative mushroom garden",
	"Cow skull, repurposed as a guildhouse",
	"Mess of closely packed shanties",
	"Neat rows of hanging wooden houses",
	"Ornate gate, guarded by statues",
	"Secret bat cult temple",
	"Beetle racing rink",
	"Storehouse, stocked with preserves",
	"Hidden riverboat dock",
	"Crumbling marble palace, built by ancient mice",
	"Scavenged human machine, working",
	"Wooden bridge connects the settlement",
	"Unnervingly tall, twisting tower",
	"Beautiful flower garden",
	"Pigeon rider’s roost",
	"Overgrown statue of an ancient hero",
	"Spiral stairwell, leading deep underground"
]
settlement_size = [
    "Farm/Manor (1-3 families)",
    "Crossroads (3-5 families)",
    "Hamlet (50-150 mice)",
    "Village (150-300 mice)",
    "Town (300-1000 mice)",
    "City (1000+ mice)"
]
settlement_governance = [
    "Guided by village elders",
    "Guided by village elders",
    "Administered by a knight or lower-caste lord",
    "Administered by a knight or lower-caste lord",
    "Organised by a guild committee",
    "Organised by a guild committee",
    "Free settlement, governed by council of burghermice",
    "Free settlement, governed by council of burghermice",
    "House of an upper caste noblemouse",
    "House of an upper caste noblemouse",
    "Seat of baronial power"
]

#See table on page 28 of rulebook
settlement_industry = [
    "Farmers, tending to towering crops",
    "Woodcutters, with saws and harnesses",
    "Rough and scarred fishermice, with nets and rafts",
    "Dark and musty mushroom farm",
    "Grains drying on every flat surface",
    "Pungent cheese, cured for years",
    "Gardens of rare herbs. Drying racks are guarded",
    "Hive of bees and their veiled keepers",
    "Merchants and traders, often in need of guards",
    "Stonemasons, working a nearby quarry",
    "Flour mill, driven by a large water-wheel",
    "Deep mine for iron, silver or tin",
    "Keep silkworms and weave fine cloth",
    "Expert explorers of caves and tunnels",
    "Kiln-fired pottery, glazed in cheerful colours",
    "Wool mill, draped in bright cloth",
    "Excellent school, rowdy pupils",
    "Bustling, well-stocked market",
    "Smelly scavenged trash pile, carefully picked over",
    "Beautiful furniture of carved and polished wood"
]
settlement_event = [
   "Disaster, everyone packing to leave",
   "Wedding, streets decked in flowers",
   "Preparing for grand seasonal feast",
   "An illness has struck",
   "Storehouse has been plundered by insects",
   "Market day, farmers flock to the settlement",
   "Mice are at each other’s throats",
   "Warband forming to defeat a beast",
   "Several children have gone missing",
   "Noblemouse makes a frivolous demand",
   "Traveling theatre troupe arrives",
   "Funeral, streets thick with smoke",
   "Conman whips up an irrational scheme",
   "Pet beetle gone mad, attacking mice",
   "Faerie emissary with an impossible request",
   "Strangely quick-growing plant nearby",
   "Valuable heirloom has a been stolen",
   "Cat lord demands a heavy tithe",
   "Coming of age ceremony for the young mice",
   "Wizard tower arrives on tortoise-back"
]
settlement_nameA = [
    "Oaks",
    "Berry",
    "Willow",
    "Stump",
    "Pine",
    "Moon",
    "Green",
    "Black",
    "Stone",
    "Hill",
    "Fig",
    "Apple",
    "Swamp",
    "Owl",
    "Fox",
    "Acorn",
    "Copper",
    "Robber",
    "Colby",
    "Drain",
    "Rose",
    "Copper",
    "Friend",
    "Trunk"
]
settlement_nameB = [
    "stand",
    "hill",
    "tower",
    "farm",
    "bridge",
    "gate",
    "creek",
    "pond",
    "nest",
    "ford",
    "grave",
    "burn",
    "thorpe",
    "ville",
    "mill",
    "dale",
    "grove",
    "town",
    "vale",
    "seed",
    "ashe",
    "bush",
    "stitch",
    "shine"
]
tavern_nameA = [
    "White",
    "Green",
    "Black",
    "Red",
    "Silver",
    "Crooked",
    "Friendly",
    "Hidden",
    "Wiley",
    "Glass",
    "Thorny",
    "Broken"
]
tavern_nameB = [
    "Beetle",
    "Fox",
    "Wedge",
    "Kernel",
    "Rat",
    "Cheese",
    "Eagle",
    "Worm",
    "Bee",
    "Lantern",
    "Rose",
    "Knight"
]
tavern_specialty = [
    "Spiced baked carrot",
    "Boiled worm broth",
    "Blackberry pie",
    "Pungent aged cheese",
    "Barley porridge",
    "Thick river-fish steak ",
    "Baked apple",
    "Fried, crumbed insect legs",
    "Fresh buttered bread",
    "Scavenged candy",
    "Honey-roasted seeds",
    "Mushroom stew"
]

