#random_adventure_table.py
#See Rulebook Page 43 for tables
creature = [
    "Fishermouse","Unruly Family","Wizard",
    "Roach Wrangler", "Farmer", "Burghermaster", "Forager",
    "Shopkeeeper", "Traveling Merchant", "Pigeon Rider",
    "Ale Brewer", "Herbalist", "Message Runner", "Vagrant",
    "Test Subject", "Tin Miner", "Baker", "Hedge Knight",
    "Tax Collector", "Matriarch", "Prospector", "Tunnellers Guild Boss",
    "Noblemouse", "Rat Bandit", "Queen Bee", "Ant Army Officer",
    "Owl Sorcerer", "Cat Lord", "Duckling", "Giant Millipede",
    "Lilliputian Ambassador", "Trapped Ghost", "Faerie Envoy",
    "Swarm of Midges", "Grandmother Spider", "Baby Bird"
]

problem = [
    "Have been accused of a crime",
    "Looking for a new home",
    "Is being followed",
    "Discovered a strange artifact",
    "Experienced an unsettling omen",
    "Want to assassinate a rival",
    "Want to retrieve lost treasure",
    "Home has been destroyed",
    "Most valued possession was stolen",
    "Has been kidnapped",
    "Has been exiled from settlement",
    "Searching for a rare cure",
    "Have lost their way",
    "Have had all their food stolen",
    "Are on the run from humans",
    "Have been waylaid by bandits",
    "Have eaten a poisonous berry",
    "Family member is missing",
    "Have lost of a lot of pips",
    "Has been accused of murder",
    "Pack tortoise is stuck",
    "Has been murdered",
    "Their home is under attack",
    "Want to steal from a rival",
    "Traveling to a new home",
    "Is hunted by enemies",
    "Want to retrieve a rare spell",
    "Want to be entertained",
    "Has lost their mother",
    "Want somewhere warm to sleep",
    "Want to reach the mouse queen",
    "Want to find their true love",
    "Want to kidnap a mouse",
    "Want to steal from a player mouse",
    "Has lost an ancient treasure",
    "Cannot get home"
]

complication = [
	"A player’s hireling is responsible",
	"Need to cross a river",
	"Antagonist is their own shadow",
	"They have amnesia",
	"The antagonist is in disguise",
	"Player mouse’s home is involved",
	"It is protected by strange beasts",
	"Antagonist is their closest friend",
	"They are the true antagonist",
	"Player mouse’s friend is involved",
	"They've been framed",
	"It's very urgent",
	"They have vital information",
	"The antagonist had a good reason",
	"They’re being tracked by a chip",
	"The antagonist is very drunk",
	"Antagonist is a family member",
	"They’re dying",
	"They’re very drunk",
	"Antagonist is a shape-shifter",
	"They’re much richer than they look",
	"Player mouse's rival is involved",
	"Antagonist wants retribution",
	"A ghost is haunting the location",
	"Their followers disagree",
	"They are badly injured",
	"It is deep in a cave",
	"They've trapped the player mice",
	"Need to get to an island",
	"Need item carried by a player mouse",
	"They don’t understand local customs",
	"They can’t leave their current location",
	"A player mouse is their target",
	"Antagonist is unusually skilled",
	"They’ve eaten it",
	"Need to climb a tree"
]